[package]
name = "analytics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
kms = ["hyperswitch_oss/kms", "external_services_oss/kms"]

[dependencies]
# First party crates
api_models = { version = "0.1.0", path = "../api_models", package = "api_models_vas" }
common_utils = { version = "0.1.0", path = "../common_utils", package = "common_utils_vas" }
external_services_oss = { workspace = true, default-features = false }
hyperswitch_oss = { workspace = true, default-features = false }
# TODO: https://github.com/juspay/hyperswitch-cloud/issues/660
masking = { version = "0.1.0", path = "../masking", package = "masking_vas"}
router_env = { version = "0.1.0", path = "../router_env", package = "router_env_vas", features = ["log_extra_implicit_fields", "log_custom_entries_to_extra"] }
storage_models = { version = "0.1.0", path = "../storage_models", package = "storage_models_vas", features = ["kv_store"] }

#Third Party dependencies
actix-web = "4.3.1"
async-trait = "0.1.68"
aws-config = { version = "0.55.3"}
aws-sdk-lambda = { version = "0.28.0"}
aws-smithy-types = { version = "0.55.3"}
bigdecimal = { version = "0.3.1", features = ["serde"] }
error-stack = "0.3.1"
futures = "0.3.28"
once_cell = "1.18.0"
reqwest = { version = "0.11.18", features = ["serde_json"] }
serde = { version = "1.0.163", features = ["derive", "rc"] }
serde_json = "1.0.96"
sqlx = { version = "0.6.3", features = ["postgres", "runtime-actix", "runtime-actix-native-tls", "time", "bigdecimal"] }
strum = { version = "0.24.1", features = ["derive"] }
thiserror = "1.0.43"
time = { version = "0.3.21", features = ["serde", "serde-well-known", "std"] }
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }