project_name_override: "hyperswitch"
package_name_override: "hyperswitch"
package_version_override: "0.1.0"
package_url_override: "https://github.com/juspay/hyperswitch"
package_author_override: "Juspay"
package_author_email_override: "support@juspay.in"
package_description_override: "Python client SDK for Hyperswitch API"
class_overrides:
  BankRedirectDataType11OpenBankingUk: "OpenBankingUkRedirectData"
  BankRedirectDataType12Przelewy24: "Przelewy24RedirectData"
  BankRedirectDataType13Sofort: "SofortRedirectData"
  BankRedirectDataType14Trustly: "TrustlyRedirectData"
  BankRedirectDataType15OnlineBankingFpx: "OnlineBankingFpxRedirectData"
  BankRedirectDataType16OnlineBankingThailand: "OnlineBankingThailandRedirectData"
  BankRedirectDataType17LocalBankRedirect: "LocalBankRedirectData"
  BankRedirectDataType18Eft: "EftRedirectData"
  BankTransferAdditionalDataType0Ach: "AchBankTransferAdditionalData"
  BankTransferAdditionalDataType1Sepa: "SepaBankTransferAdditionalData"
  BankTransferAdditionalDataType2Bacs: "BacsBankTransferAdditionalData"
  BankTransferAdditionalDataType3Multibanco: "MultibancoBankTransferAdditionalData"
  BankTransferAdditionalDataType4Permata: "PermataBankTransferAdditionalData"
  BankTransferAdditionalDataType5Bca: "BcaBankTransferAdditionalData"
  BankTransferAdditionalDataType6BniVa: "BniVaBankTransferAdditionalData"
  BankTransferAdditionalDataType7BriVa: "BriVaBankTransferAdditionalData"
  BankTransferAdditionalDataType8CimbVa: "CimbVaBankTransferAdditionalData"
  BankTransferAdditionalDataType9DanamonVa: "DanamonVaBankTransferAdditionalData"
  BankTransferAdditionalDataType10MandiriVa: "MandiriVaBankTransferAdditionalData"
  BankTransferAdditionalDataType12Pse: "PseBankTransferAdditionalData"
  BankTransferAdditionalDataType14InstantBankTransfer: "InstantBankTransferAdditionalData"
  BankTransferDataType0AchBankTransfer: "AchBankTransferData"
  BankTransferDataType1SepaBankTransfer: "SepaBankTransferData"
  BankTransferDataType2BacsBankTransfer: "BacsBankTransferData"
  BankTransferDataType3MultibancoBankTransfer: "MultibancoBankTransferData"
  BankTransferDataType4PermataBankTransfer: "PermataBankTransferData"
  BankTransferDataType5BcaBankTransfer: "BcaBankTransferData"
  BankTransferDataType6BniVaBankTransfer: "BniVaBankTransferData"
  BankTransferDataType7BriVaBankTransfer: "BriVaBankTransferData"
  BankTransferDataType8CimbVaBankTransfer: "CimbVaBankTransferData"
  BankTransferDataType9DanamonVaBankTransfer: "DanamonVaBankTransferData"
  BankTransferDataType10MandiriVaBankTransfer: "MandiriVaBankTransferData"
  BankTransferDataType11Pix: "PixBankTransferData"
  BankTransferDataType12Pse: "PseBankTransferData"
  BankTransferDataType13LocalBankTransfer: "LocalBankTransferData"
  BankTransferDataType14InstantBankTransfer: "InstantBankTransferData"
  GiftCardAdditionalDataType1PaySafeCard: "PaySafeCardAdditionalData"
  GiftCardDataType1PaySafeCard: "PaySafeCardData"
  PaymentMethodDataResponseType7MandatePayment: "MandatePaymentDataResponse"
  PaymentMethodDataResponseType8Reward: "RewardPaymentDataResponse"
  WalletDataType11DanaRedirect: "DanaRedirectWalletData"
  WalletDataType21TwintRedirect: "TwintRedirectWalletData"
  WalletDataType22VippsRedirect: "VippsRedirectWalletData" 