admin_api_key = "test_admin"
merchant_id = "test_merchant_f5fc9b5e"
profile_id = "pro_3Zpor02153S82p0mKIOr"
api_key = "snd_Pv9xREA8gvegnChRCo2cVq6ykWZAEzpCZrtnauZGB6m8gxUAwiWKXtQtNayR7IAn"
api_key_id = "snd_wSUCNgFRVS8t5OWwDEmY"
connector_id = "mca_BsLkPD3U4iA4XMn3oz9M"
