acknowledgements:
  enabled: true

api:
  enabled: true
  address: 0.0.0.0:8686

sources:
  kafka_payments:
    type: kafka
    bootstrap_servers: kafka0:29092
    group_id: sessionizer
    topics:
      - ^hyperswitch-*

transforms:
  parse_kafka_payments:
    type: remap
    inputs:
      - kafka_payments
    source: >-
      payment_topic_to_log_type = {
        "hyperswitch-payment-intent-events" : "intent",
        "hyperswitch-payment-attempt-events" : "attempt",
        "hyperswitch-dispute-events" : "dispute",
        "hyperswitch-refund-events" : "refund"
      };
      .log = parse_json(.message) ?? {};
      del(.message);
      .log_type = get(payment_topic_to_log_type, [.topic]) ?? "unknown";

  filter_out_negatives:
    type: filter
    inputs:
      - parse_kafka_payments
    condition: .log.sign_flag == 1

  init_sessionizer_vars:
    type: remap
    inputs:
      - filter_out_negatives
    source: >-
      log(.);
      .sessionizer = {
        "table": "${CASSANDRA_TABLE:-payments}",
        "id": string!(.log.merchant_id) + "_" + string!(.log.payment_id),
        "db_log_type": "intent"
      };

  buffer_with_reduce:
    type: reduce
    inputs:
      - init_sessionizer_vars
    group_by:
      - log.log_type
      - log.merchant_id
      - log.payment_id
      - log.attempt_id
      - log.refund_id
      - log.dispute_id
    merge_strategies:
      log: retain
    expire_after_ms: 5000

  cassandra_get_old_event:
    type: lua
    inputs:
      - buffer_with_reduce
    version: "2"
    hooks:
      init: init
      process: process
      shutdown: shutdown
    source: |-
      local socket = require 'socket'
      local cassandra = require "cassandra"

      function sleep(sec)
        socket.select(nil, nil, sec)
      end

      function client_connect()
        assert(client:connect())
      end

      function client_close()
        assert(client:close())
      end

      function create_cassandra_connection()
        client = assert(cassandra.new {
          host = os.getenv("CASSANDRA_HOST") or "cassandra0",
          port = os.getenv("CASSANDRA_PORT") or 9042,
          keyspace = os.getenv("CASSANDRA_KEYSPACE") or "sessionizer",
          auth = cassandra.auth_providers.plain_text(os.getenv("CASSANDRA_USERNAME") or "cassandra", os.getenv("CASSANDRA_PASSWORD") or "cassandra"),
          ssl = os.getenv("CASSANDRA_SSL") or false,
          cert = os.getenv("CASSANDRA_CERT") or ""
        })

        client:settimeout(1000)
        client:setkeepalive(0)
        client_connect()
      end

      function init(emit)
        create_cassandra_connection()  
      end

      function db_get(table, id, version)
        local version = version or 1
        local rows = assert(client:execute(string.format("SELECT * FROM %s WHERE id = ?", table), {
          id
        }))
        return rows
      end

      function db_get_wait(table, id, version)
        local is_success, data = pcall(db_get, table, id, version)
        while not is_success do
          sleep(5)

          print(string.format("db_get - recreate cassandra connection start - reason - %s", data))
          local connection_closed, err = pcall(client_close)
          print(string.format("db_get - close old cassandra connection - result - %s, %s", connection_closed, err))
          local connection_success, err = pcall(create_cassandra_connection)
          print(string.format("db_get - recreate cassandra connection end - result - %s, %s", connection_success, err))

          is_success, data = pcall(db_get, table, id, version)
        end

        return data
      end

      function process(event, emit)
        local sessionizer = event.log.sessionizer

        local data = db_get_wait(sessionizer.table, sessionizer.id)
        event.log.old_log_type = sessionizer.db_log_type
        if #data == 1 then
          event.log.old_log = data[1].state
        end

        emit(event)
      end

      function shutdown(emit)
        client:close()
      end

  club_with_old_event:
    type: remap
    inputs:
      - cassandra_get_old_event
    source: >-
      db_log = .old_log;
      new_log_type = .log_type;
      new_log = .log;

      traverse_map = if new_log_type == "intent" {
        {}
      } else if new_log_type == "attempt" {
        {"attempts": new_log.attempt_id}
      } else if new_log_type == "refund" {
        {"attempts": new_log.attempt_id, "refunds": new_log.refund_id}
      } else if new_log_type == "dispute" {
        {"attempts": new_log.attempt_id, "disputes": new_log.dispute_id}
      } else {
        null
      }

      .sessionizer.db_event = "{}";
      if is_object(traverse_map) {
        traverse_map = object!(traverse_map);
        path = [];
        for_each(traverse_map) -> |k, v| {
          path = append(path, [k, v])
        }
        db_log = parse_json(db_log) ?? {};
        log = get(db_log, path) ?? {};

        new_log = object(new_log) ?? {};
        for_each(new_log) -> |k, v| {
          log = set!(log, [k], v)
        };

        .log = set!(db_log, path, log)
        .sessionizer.db_event = encode_json(.log)
      }

  cassandra_set_new_event:
    type: lua
    inputs:
      - club_with_old_event
    version: "2"
    hooks:
      init: init
      process: process
      shutdown: shutdown
    source: |-
      local socket = require 'socket'
      local cassandra = require "cassandra"

      function sleep(sec)
        socket.select(nil, nil, sec)
      end

      function client_connect()
        assert(client:connect())
      end

      function client_close()
        assert(client:close())
      end

      function create_cassandra_connection()
        client = assert(cassandra.new {
          host = os.getenv("CASSANDRA_HOST") or "cassandra0",
          port = os.getenv("CASSANDRA_PORT") or 9042,
          keyspace = os.getenv("CASSANDRA_KEYSPACE") or "sessionizer",
          auth = cassandra.auth_providers.plain_text(os.getenv("CASSANDRA_USERNAME") or "cassandra", os.getenv("CASSANDRA_PASSWORD") or "cassandra"),
          ssl = os.getenv("CASSANDRA_SSL") or false,
          cert = os.getenv("CASSANDRA_CERT") or ""
        })

        client:settimeout(1000)
        client:setkeepalive(0)
        client_connect()
      end

      function init(emit)
        create_cassandra_connection()
      end

      function db_set(table, state, id, version)
        version = version or 1
        local res = assert(client:execute(string.format("INSERT INTO %s (id, state, version) VALUES (?, ?, ?)", table), {
          id,
          state,
          version
        },{consistency = cassandra.consistencies.local_quorum}))
        return res
      end

      function db_set_wait(table, state, id, version)
        local is_success, res = pcall(db_set, table, state, id, version)

        while not is_success do
          sleep(5)

          print(string.format("db_set - recreate cassandra connection start - reason - %s", data))
          local connection_closed, err = pcall(client_close)
          print(string.format("db_set - close old cassandra connection - result - %s, %s", connection_closed, err))
          local connection_success, err = pcall(create_cassandra_connection)
          print(string.format("db_set - recreate cassandra connection end - result - %s, %s", connection_success, err))

          is_success, res = pcall(db_set, table, state, id, version)
        end

        return res
      end

      function process(event, emit)
        local sessionizer = event.log.sessionizer
        local new_event_insert = db_set_wait(sessionizer.table, sessionizer.db_event, sessionizer.id)
        emit(event)
      end

      function shutdown(emit)
        client:close()
      end

  generate_signed_events:
    type: remap
    inputs:
      - cassandra_set_new_event
    source: >-
      events = [];
      if exists(.old_log) {
        .old_log = parse_json!(.old_log);
        .old_log.sign_flag = -1;
        events = push(events, .old_log);
      };
      .log.sign_flag = 1;
      events = push(events, .log);
      . = events

  consolidate_events:
    type: remap
    inputs:
      - generate_signed_events
    source: >-
      attempts = object(.attempts) ?? {};
      attempt_total_count = 0;
      attempt_total_amount = 0;
      attempt_success_count = 0;
      attempt_success_amount = 0;

      for_each(attempts) -> |attempt_id, attempt| {

        attempt_log = object(attempt) ?? {};

        attempt_total_count = attempt_total_count + 1;
        attempt_total_amount = attempt_total_amount + to_float(attempt_log.amount) ?? 0;
        if attempt_log.status == "charged" {
          attempt_success_count = attempt_success_count + 1;
          attempt_success_amount = attempt_success_amount + to_float(attempt_log.amount) ?? 0;
        }

        refunds = object(attempt_log.refunds) ?? {};
        refund_total_count = 0;
        refund_total_amount = 0;
        refund_success_count = 0;
        refund_success_amount = 0;

        for_each(refunds) -> |_refund_id, refund| {
          refund_log = object(refund) ?? {};
          
          refund_total_count = refund_total_count + 1;
          refund_total_amount = refund_total_amount + to_float(refund_log.refund_amount) ?? 0;
          if refund_log.status == "succeeded" {
            refund_success_count = refund_success_count + 1;
            refund_success_amount = refund_success_amount + to_float(refund_log.refund_amount) ?? 0;
          }
        }

        .refund_total_count = refund_total_count + to_int(.refund_total_count) ?? 0;
        .refund_total_amount = refund_total_amount + to_float(.refund_total_amount) ?? 0;
        .refund_success_count = refund_success_count + to_int(.refund_success_count) ?? 0;
        .refund_success_amount = refund_success_amount + to_float(.refund_success_amount) ?? 0;

        attempt_log.refund_total_count = refund_total_count;
        attempt_log.refund_total_amount = refund_total_amount;
        attempt_log.refund_success_count = refund_success_count;
        attempt_log.refund_success_amount = refund_success_amount;

        disputes = object(attempt_log.disputes) ?? {};
        dispute_total_count = 0;
        dispute_total_amount = 0;
        dispute_success_count = 0;
        dispute_success_amount = 0;

        for_each(disputes) -> |_dispute_id, dispute| {
          dispute_log = object(dispute) ?? {};

          dispute_total_count = dispute_total_count + 1;
          dispute_total_amount = dispute_total_amount + to_float(dispute_log.dispute_amount) ?? 0;
          if dispute_log.dispute_status == "dispute_won" {
            dispute_success_count = dispute_success_count + 1;
            dispute_success_amount = dispute_success_amount + to_float(dispute_log.dispute_amount) ?? 0;
          }
        }

        .dispute_total_count = dispute_total_count + to_int(.dispute_total_count) ?? 0;
        .dispute_total_amount = dispute_total_amount + to_float(.dispute_total_amount) ?? 0;
        .dispute_success_count = dispute_success_count + to_int(.dispute_success_count) ?? 0;
        .dispute_success_amount = dispute_success_amount + to_float(.dispute_success_amount) ?? 0;

        attempt_log.dispute_total_count = dispute_total_count;
        attempt_log.dispute_total_amount = dispute_total_amount;
        attempt_log.dispute_success_count = dispute_success_count;
        attempt_log.dispute_success_amount = dispute_success_amount;

        .attempts = set!(.attempts, [attempt_id], attempt_log)
      }

      .attempt_total_count = attempt_total_count + to_int(.attempt_total_count) ?? 0;
      .attempt_total_amount = attempt_total_amount + to_float(.attempt_total_amount) ?? 0;
      .attempt_success_count = attempt_success_count + to_int(.attempt_success_count) ?? 0;
      .attempt_success_amount = attempt_success_amount + to_float(.attempt_success_amount) ?? 0;

  consolidate_events_intents:
    type: remap
    inputs:
      - consolidate_events
    source: >-
      del(.attempts);
      .sessionizer_key = string!(.merchant_id) + "_" + string!(.payment_id);
      # .log_type = "intent";

  consolidate_events_attempts:
    type: remap
    inputs:
      - consolidate_events
    source: >-
      . = if exists(.attempts) {
        map_values(values(object!(.attempts))) -> |a| {
          attempt = object!(a);
          del(attempt.refunds);
          del(attempt.disputes);
          attempt.sign_flag = .sign_flag;
          # attempt.log_type = "attempt";
          attempt.sessionizer_key = string!(attempt.merchant_id) + "_" + string!(attempt.payment_id) + "_" + string!(attempt.attempt_id);
          attempt
        }
      } else {
        []
      }

  consolidate_events_refunds:
    type: remap
    inputs:
      - consolidate_events
    source: >-
      . = if exists(.attempts) {
        flatten(map_values(values(object!(.attempts))) -> |a| {
          attempt = object!(a);
          if exists(attempt.refunds) {
            map_values(values(object!(attempt.refunds))) -> |r| {
              refund = object!(r);
              refund.sign_flag = .sign_flag;
              # refund.log_type = "refund";
              refund.sessionizer_key = string!(refund.merchant_id) + "_" + string!(refund.payment_id) + "_" + string!(refund.attempt_id) + "_" + string!(refund.refund_id);
              refund
            }
          } else {
            []
          }
        })
      } else {
        []
      }

  consolidate_events_disputes:
    type: remap
    inputs:
      - consolidate_events
    source: >-
      . = if exists(.attempts) {
        flatten(map_values(values(object!(.attempts))) -> |a| {
          attempt = object!(a);
          if exists(attempt.disputes) {
            map_values(values(object!(attempt.disputes))) -> |d| {
              dispute = object!(d);
              dispute.sign_flag = .sign_flag;
              # dispute.log_type = "dispute";
              dispute.sessionizer_key = string!(dispute.merchant_id) + "_" + string!(dispute.payment_id) + "_" + string!(dispute.attempt_id) + "_" + string!(dispute.dispute_id);
              dispute
            }
          } else {
            []
          }
        })
      } else {
        []
      }

sinks:
  # kafka_intents_sink:
  #   type: kafka
  #   inputs:
  #     - consolidate_events_intents
  #   bootstrap_servers: kafka0:29092
  #   topic: consolidated-intent-events
  #   key_field: sessionizer_key
  #   encoding:
  #     codec: json

  console_intents:
    inputs:
      - consolidate_events_intents
    target: stdout
    type: console
    encoding:
      codec: json

  console_attempts:
    inputs:
      - consolidate_events_attempts
    target: stdout
    type: console
    encoding:
      codec: json

  console_refunds:
    inputs:
      - consolidate_events_refunds
    target: stdout
    type: console
    encoding:
      codec: json

  console_disputes:
    inputs:
      - consolidate_events_disputes
    target: stdout
    type: console
    encoding:
      codec: json
